language: rust
sudo: required
dist: xenial

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-apple-darwin
      os: osx

before_install:
- |
  rustup target add $TARGET
  # download libunwind and build a static version w/ musl-gcc if needed
  if [ $TARGET = x86_64-unknown-linux-musl ]; then
      wget https://github.com/libunwind/libunwind/releases/download/v1.3.1/libunwind-1.3.1.tar.gz
      tar -zxvf libunwind-1.3.1.tar.gz
      cd libunwind-1.3.1/
      CC=musl-gcc ./configure --disable-minidebuginfo --enable-ptrace --disable-tests --disable-documentation
      make
      sudo make install
  fi

script:
  - cargo test --verbose --target $TARGET

addons:
  apt:
    packages:
    - libunwind-dev
    - g++-multilib
    - musl-tools
