language: python

matrix:
  include:
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2

script:
  - $PIP install cibuildwheel setuptools_rust
  - export CIBW_BEFORE_BUILD='pip install setuptools-rust && source {project}/ci/install_rust.sh'
  - export CIBW_SKIP='cp2* cp33-* cp34-* cp35-* $CIBW_SKIP'
  - export CIBW_ENVIRONMENT='PATH="$HOME/rust/bin:$PATH"'
  - cibuildwheel --output-dir wheelhouse
