[package]
name = "py-spy"
version = "0.1.1"
authors = ["Ben Frederickson <github@benfrederickson.com>"]
repository = "https://github.com/benfred/py-spy"
readme = "README.md"
exclude = ["images/*"]

[dependencies]
clap = "2"
console = "0.6.1"
indicatif = "0.9.0"
failure = "0.1.1"
goblin = "0.0.15"
libc = "0.2.34"
regex = "1"
tempdir = "0.3"
proc-maps = {git = "https://github.com/benfred/proc-maps.git", branch="master"}
read-process-memory = {git = "https://github.com/benfred/read-process-memory.git", branch = "master"}
python-bindings = {path = "python-bindings"}

[target.'cfg(unix)'.dependencies]
termios = "0.2.2"

[target.'cfg(windows)'.dependencies]
winapi = {git = "https://github.com/benfred/winapi-rs.git", branch= "0.3", features = ["winbase", "consoleapi", "wincon", "handleapi", "processenv" ]}
